version: '3.7'
volumes:
  database:

services:
  speedtest:
    container_name: speedtest
    image: s
    restart: always
    environment:
      MODE: frontend
      #TITLE: "LibreSpeed"
      TELEMETRY: "true"
      ENABLE_ID_OBFUSCATION: "true"
      REDACT_IP_ADDRESSES: "false"
      #PASSWORD:
      #EMAIL:
      #DISABLE_IPINFO: "false"
      #IPINFO_APIKEY: "your api key"
      #DISTANCE: "km"
      #WEBPORT: 8080
    ports:
      - "80:8080" # webport mapping (host:container)
    volumes:
        - $PWD/speedtest/servers.json:/servers.json
        - $PWD/speedtest/db/:/database
