version: '3.7'
services:
  speedtest:
    container_name: speedtest
    image: st
    build: ./data
    restart: always
    environment:
      MODE: frontend
      TITLE: "LibreSpeed"
      TELEMETRY: "true"
      ENABLE_ID_OBFUSCATION: "true"
      REDACT_IP_ADDRESSES: "false"
      WEBPORT: 8080

      DB_TYPE: mysql
      DB_USERNAME: user
      DB_PASSWORD: pass
      DB_HOSTNAME: mysql_container
      DB_NAME: speedtest_telemetry
    ports:
      - 80:8080
    volumes:
      - $PWD/data/servers.json:/servers.json
    networks: 
      - web

  mysql:
     image: mysql:8.0
     container_name: mysql_container
     environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: myShema
     ports:
       - "3306:3306"
     volumes:
       - $PWD/data:/home
       - db:/var/lib/mysql
     networks:
       - web
volumes:
  db:

networks:
    web:
      name: proxy_web
      #      external: true
