name: app

services:
  speedtest:
    container_name: speedtest
    image: st
    build: ./data
    restart: always
    environment:
      MODE: frontend
      TITLE: "LibreSpeed"
      TELEMETRY: "true"
      ENABLE_ID_OBFUSCATION: "true"
      REDACT_IP_ADDRESSES: "false"
      WEBPORT: 8080

      DB_TYPE: mysql
      DB_USERNAME: user
      DB_PASSWORD: pass
      DB_HOSTNAME: mysql
      DB_NAME: speedtest_telemetry
    volumes:
      - $PWD/data/servers.json:/servers.json
    networks: 
      - web
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: speedtest.access

  mysql:
     image: mysql:8.0
     container_name: mysql
     environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: myShema
     ports:
       - "3306:3306"
     volumes:
       - $PWD/data:/home
       - db:/var/lib/mysql
     networks:
       - web
     restart: always
     logging:
       driver: "fluentd"
       options:
         fluentd-address: localhost:24224
         tag: mysql.access

  proxy:
     image: caddy
     container_name: proxy
     restart: unless-stopped
     cap_add:
       - NET_ADMIN
     ports:
       - "80:80"
     volumes:
       - $PWD/data/caddy/conf:/etc/caddy
       - $PWD/data/caddy/site:/srv
       - caddy_data:/data
       - caddy_config:/config
     networks:
       - web
     logging:
       driver: "fluentd"
       options:
         fluentd-address: localhost:24224
         tag: proxy.access

volumes:
  db:
  caddy_data:
  caddy_config:

networks:
    web:
      name: proxy_web
      external: true
