version: "3"
services:
  fluentd:
    image: sviridenkomaxim/rebrain:fluentd
    volumes:
      - ./data/fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"  
    networks:
            - traefik

  elasticsearch:
    image: elasticsearch:7.13.1
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node" 
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
            - traefik

  kibana:
    image: kibana:7.13.1
    deploy:        
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.kibana.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=rebrainme:$$apr1$$PGGQJIeM$$Bbpyd/WmYWGIrN5nhG3Bd/"
        - "traefik.http.routers.kibana.rule=Host(`kibana.158.160.5.175.nip.io`)"
        - "traefik.http.services.kibana-service.loadbalancer.server.port=5601"
    networks:
            - traefik

networks:
  traefik:
    name: proxy_web
    attachable: true
