version: "3"
services:
  fluentd:
    image: sviridenkomaxim/rebrain:fluentd
    container_name: fluentd
    volumes:
      - ./data/fluentd/conf:/fluentd/etc
      - ./data/fluentd/log:/fluentd/log
    ports:
      - "24224:24224"
      - "24224:24224/udp"  
    networks:
      - proxy

  elasticsearch:
    image: elasticsearch:7.13.1
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node" 
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - es:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - proxy

  kibana:
    image: kibana:7.13.1
    container_name: kibana_container
    ports:
      - 5601:5601
    networks:
      - proxy
    depends_on: 
        fluentd:
                condition: service_started
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: kibana.access

volumes:
        es:

networks:
  proxy:
    name: proxy_web
    attachable: true
